name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issues and PRs
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN}}
          assignees: Tristan-Stoltz-ERC
          numOfAssignee: 1
          abortIfPreviousAssignees: true
